version: '2.3'

services:

## Kibana service
  kibana:
    build: .
    container_name: kibana
    restart: always
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    ports:
     - "0.0.0.0:5601:5601"
    image: "dtagdevsec/kibana:2204"
